version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - my-network
  backend:
    image: ghcr.io/chienduynguyen1702/golang-swagger:latest
    container_name: golang
    ports:
      - "8089:8080"
    env_file:
      - .env
    networks:
      - my-network
networks:
  my-network:
    driver: bridge